name: Using actions

on: workflow_dispatch

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./03-using-actions/react-app
        # Checkout the repository
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              # Install dependencies
            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '20.x'
            - name: Install dependencies
              run: npm install

            - name: Run tests
              run: npm test




        

        # Execute tests