name: Using actions

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        # Checkout the repository
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '20.x'
            - name: Install dependencies
              run: npm install
              working-directory: ./03-using-actions/react-app



        # Install dependencies

        # Execute tests